name: my-go-cli-project
version: 1.0.0
database:
  host: localhost
  port: 5432
  username: myuser
  password: mypassword
  database: mydatabase
logging:
  level: info
  file: /var/log/my-go-cli-project.log
api:
  endpoint: https://api.example.com
  key: myapikey